version: "2"

services:
  app:
    image: golang:alpine
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: go run main.go
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379

  redis:
    image: redis:alpine