version: "2"

services:
  app:
    image: golang:alpine
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: go run main.go
    depends_on:
      - mongo
    environment:
      MONGODB_ADDRESS: mongo
      MONGODB_NAME: test
    ports:
      - "8080" 

  mongo:
    image: mongo